
export interface PopularAsset {
    symbol: string;
    name: string;
    type: 'crypto' | 'stock' | 'etf';
}

export const POPULAR_ASSETS: PopularAsset[] = [
    // --- STOCKS ---
    { symbol: 'AAPL', name: 'Apple', type: 'stock' },
    { symbol: 'MSFT', name: 'Microsoft', type: 'stock' },
    { symbol: 'GOOGL', name: 'Google (Alphabet)', type: 'stock' },
    { symbol: 'AMZN', name: 'Amazon', type: 'stock' },
    { symbol: 'TSLA', name: 'Tesla', type: 'stock' },
    { symbol: 'NVDA', name: 'NVIDIA', type: 'stock' },
    { symbol: 'META', name: 'Meta (Facebook)', type: 'stock' },
    { symbol: 'NFLX', name: 'Netflix', type: 'stock' },
    { symbol: 'COIN', name: 'Coinbase', type: 'stock' },
    { symbol: 'PLTR', name: 'Palantir', type: 'stock' },
    { symbol: 'AMD', name: 'AMD', type: 'stock' },
    { symbol: 'INTC', name: 'Intel', type: 'stock' },
    { symbol: 'ORCL', name: 'Oracle', type: 'stock' },
    { symbol: 'CRM', name: 'Salesforce', type: 'stock' },
    { symbol: 'UBER', name: 'Uber', type: 'stock' },
    { symbol: 'SPOT', name: 'Spotify', type: 'stock' },
    { symbol: 'DIS', name: 'Disney', type: 'stock' },
    { symbol: 'V', name: 'Visa', type: 'stock' },
    { symbol: 'MA', name: 'Mastercard', type: 'stock' },
    { symbol: 'JPM', name: 'JPMorgan Chase', type: 'stock' },
    { symbol: 'BAC', name: 'Bank of America', type: 'stock' },
    { symbol: 'WMT', name: 'Walmart', type: 'stock' },
    { symbol: 'PYPL', name: 'PayPal', type: 'stock' },
    { symbol: 'SHOP', name: 'Shopify', type: 'stock' },
    { symbol: 'SQ', name: 'Block (Square)', type: 'stock' },
    { symbol: 'RBLX', name: 'Roblox', type: 'stock' },
    { symbol: 'SNAP', name: 'Snapchat', type: 'stock' },
    { symbol: 'HOOD', name: 'Robinhood', type: 'stock' },

    // --- CRYPTO ---
    { symbol: 'BTC-USD', name: 'Bitcoin BTC', type: 'crypto' },
    { symbol: 'ETH-USD', name: 'Ethereum ETH', type: 'crypto' },
    { symbol: 'SOL-USD', name: 'Solana SOL', type: 'crypto' },
    { symbol: 'XRP-USD', name: 'Ripple XRP', type: 'crypto' },
    { symbol: 'BNB-USD', name: 'BNB Binance Coin', type: 'crypto' },
    { symbol: 'ADA-USD', name: 'Cardano ADA', type: 'crypto' },
    { symbol: 'DOGE-USD', name: 'Dogecoin DOGE', type: 'crypto' },
    { symbol: 'AVAX-USD', name: 'Avalanche AVAX', type: 'crypto' },
    { symbol: 'DOT-USD', name: 'Polkadot DOT', type: 'crypto' },
    { symbol: 'MATIC-USD', name: 'Polygon MATIC', type: 'crypto' },
    { symbol: 'LINK-USD', name: 'Chainlink LINK', type: 'crypto' },
    { symbol: 'UNI-USD', name: 'Uniswap UNI', type: 'crypto' },
    { symbol: 'LTC-USD', name: 'Litecoin LTC', type: 'crypto' },
    { symbol: 'ATOM-USD', name: 'Cosmos ATOM', type: 'crypto' },
    { symbol: 'NEAR-USD', name: 'NEAR Protocol', type: 'crypto' },
    { symbol: 'APT-USD', name: 'Aptos APT', type: 'crypto' },
    { symbol: 'ARB-USD', name: 'Arbitrum ARB', type: 'crypto' },
    { symbol: 'OP-USD', name: 'Optimism OP', type: 'crypto' },
    { symbol: 'WLD-USD', name: 'Worldcoin WLD', type: 'crypto' },
    { symbol: 'SUI-USD', name: 'Sui SUI', type: 'crypto' },
    { symbol: 'PEPE-USD', name: 'Pepe PEPE', type: 'crypto' },
    { symbol: 'SHIB-USD', name: 'Shiba Inu SHIB', type: 'crypto' },
    { symbol: 'TRX-USD', name: 'TRON TRX', type: 'crypto' },
    { symbol: 'TON-USD', name: 'Toncoin TON', type: 'crypto' },
    { symbol: 'HBAR-USD', name: 'Hedera HBAR', type: 'crypto' },
    { symbol: 'ICP-USD', name: 'Internet Computer ICP', type: 'crypto' },
    { symbol: 'FIL-USD', name: 'Filecoin FIL', type: 'crypto' },
    { symbol: 'INJ-USD', name: 'Injective INJ', type: 'crypto' },
    { symbol: 'MKR-USD', name: 'Maker MKR', type: 'crypto' },
    { symbol: 'AAVE-USD', name: 'Aave AAVE', type: 'crypto' },
    { symbol: 'GRT-USD', name: 'The Graph GRT', type: 'crypto' },
    { symbol: 'FTM-USD', name: 'Fantom FTM', type: 'crypto' },
    { symbol: 'ALGO-USD', name: 'Algorand ALGO', type: 'crypto' },
    { symbol: 'XLM-USD', name: 'Stellar XLM', type: 'crypto' },
    { symbol: 'VET-USD', name: 'VeChain VET', type: 'crypto' },

    // --- ETFs / Index ---
    { symbol: 'SPY', name: 'S&P 500 ETF (US)', type: 'etf' },
    { symbol: 'QQQ', name: 'Nasdaq 100 ETF (US)', type: 'etf' },
    { symbol: 'VOO', name: 'Vanguard S&P 500 (US)', type: 'etf' },
    { symbol: 'VTI', name: 'Vanguard Total Market (US)', type: 'etf' },
    { symbol: 'VUAG.L', name: 'Vanguard S&P 500 Acc (EU)', type: 'etf' },
    { symbol: 'VUSA.L', name: 'Vanguard S&P 500 Dist (EU)', type: 'etf' },
    { symbol: 'VWCE.DE', name: 'Vanguard All-World Acc (EU)', type: 'etf' },
    { symbol: 'IWDA.AS', name: 'iShares MSCI World Acc (EU)', type: 'etf' },
    { symbol: 'CSPX.L', name: 'iShares Core S&P 500 Acc', type: 'etf' },
    { symbol: 'EUNL.DE', name: 'iShares Core MSCI World EUR', type: 'etf' },
    { symbol: 'SGLD.L', name: 'Invesco Gold ETC', type: 'etf' },
    { symbol: 'GLD', name: 'SPDR Gold Shares', type: 'etf' },
];

